### ISSUE TITLE
Implement new zk dsl

### ISSUE THREAD

**Issue by swjng** [jeong0982/zkdsl-wip#1]
## Abstract
A new dsl should provide
1. Composability and compatibility
2. Security
3. Expressiveness and authority
4. Performance

*refer to [zkDSL design principles](https://hackmd.io/@soowon/SJTeCjRwn)*
## Design
*refer to [zk DSL](https://hackmd.io/@soowon/H1wJViPRTJ-h3F9QNEBXxg)*

Turing Machine computation is proved by the VM (via a DSL compiled to the VM instructions) and special arithmetic constraints can be accessed directly (outside of VM instructions). By this, this dsl is Turing-complete, meaning it can express any existing program. And it means that it will reduce underconstrained circuit problems.

### TODOs
- [ ] IVC
    - [ ] Write a circuit of vm
    - [ ] Design IVC structure for internal
- [ ] abstract machine
    - [ ] IR (Instructions)
    - [ ] Stack based virtual machine
    - [ ] Memory abstraction (not RAM)
- [ ] Language features
    - [ ] Type system
    - [ ] Modular structure (function declaration)
    - [ ] Direct constraint generation

### Longterm goal
- [ ] formal verification
    - [ ] Operational semantic
    - [ ] Verify equivalence of frontend code and vm behavior
    - [ ] Verify compilation
